### ISSUE TITLE
Stream topics - what when? 

### ISSUE THREAD

**Issue by kmgrime** [mtheoryx/roberttables-livestream#16]
I would like to know what the topics we are running in advance, like a list of stuff you are running. If you are on a project there is probably alots of stuff included there, maybe a list of what you are going through in that project. That will probably make it easier to group youtube videoes of what projects you are running etc.

**Comment by mtheoryx** [comment]
If I'm reading this right (and feel free to correct me), I hear you suggesting we could add:

- Better exporting/grouping of youtube videos in a playlist
- Better resources on the history of the project, and resources for the project, stored somewhere
- I need to get better about stream titles for topics (for the stream, youtube, and my tweets)
- Add some "today on" info to tweet announcements

Any other ways that would help? Better info panel material? I have one panel below the stream, and a today command now. Maybe those could be enhanced?

Maybe better panels, and a separate "working on" vs "today" commands since we do different projects on different streams?

**Comment by kmgrime** [comment]
Yes totally correct!
   I have nothing to add to your bullets, spot on sir!
Does the !today command only bring project or also tools and subjects in the project? Do you have some kind of "masterlist" of stuff you want to go through or work on at stream? If not maybe an read only list here?

**Comment by mtheoryx** [comment]
I've created a master list in the README.md of the stream here:

https://github.com/mtheoryx/roberttables-livestream/blob/master/README.md

The today command is something I have to keep up on each time to change to specifically what "today" will work on.

**Comment by mtheoryx** [comment]
We finally have a stream site we can start working with @w4zz !!

So, we have 2 things we can leverage (well 3 really):

- A projects page (for longer-term projects) with a page for each project (this could maybe later be refactored to be a mini-blog for each iteration of the project, or just linked back to the stream notes for the day we worked on that project)
- Published stream notes with categories (Hardware/Software/IRL/etc) We need to add support for filtering by category
- Also stream notes could have a new "tag" that will identify what "projects" were being worked on during that stream (similar to above point where a project could have links back to the stream entries that involved the project)

These are all things I can definitely work on asap. The youtube export and categorization and whatnot is a much larger effort that I'm not even 100% sure I really want to pursue. I don't care that much about youtube at the moment, and certainly don't care for the majority of the features or audience, or the extra work of supporting a whole other plattform.

What are your thoughts on the things I know I can do? Do they address some of your ideas?

Cheers!
